python3: set 'fork' start method
In Python 3 start method 'spawn' in multiprocessing module becomes
default on Mac OS [1]. However 'spawn' method requires object
serialization that doesn't work when objects use lambdas, whose for
example used in class TestSuite (lib/test_suite.py). So this method is
not acceptable for using with test-run. To workaround it can be possible
to force fork mode with multiprocessing.set_start_method('fork').

Start method is available on Python 3 only:

Traceback (most recent call last):
  File "../../test/test-run.py", line 227, in <module>
    multiprocessing.set_start_method('fork')
AttributeError: 'module' object has no attribute 'set_start_method'

1. https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods.

Fixes #265
Part of #20